name: Development Build

on:
  push:
    branches: 
      - main
      - develop
  workflow_dispatch: # Allows manual triggering

jobs:
  dev-build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false
        
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
      
    - name: Run tests
      run: ./gradlew test --stacktrace
      continue-on-error: true
      
    - name: Generate build info
      run: |
        echo "Build Date: $(date)" > build-info.txt
        echo "Commit: ${{ github.sha }}" >> build-info.txt
        echo "Branch: ${{ github.ref_name }}" >> build-info.txt
        echo "Actor: ${{ github.actor }}" >> build-info.txt
        
    - name: Upload development build
      uses: actions/upload-artifact@v4
      with:
        name: penguinlib-dev-${{ github.sha }}
        path: |
          build/libs/*.jar
          build-info.txt
        retention-days: 14
        
    - name: Comment on commit (if failed)
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: '❌ Build failed! Check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
          })
