name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: PenguinLib ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## PenguinLib ${{ steps.get_version.outputs.VERSION }}
          
          ### Changes in this version:
          - Successfully ported from NeoForged to Forge 1.20.1
          - Updated all systems for compatibility with Forge 1.20.1
          - Fixed event bus registration and networking
          - Updated build system and configuration
          
          ### Installation:
          1. Download the JAR file below
          2. Install Minecraft Forge 1.20.1 (version 47.1.0 or later)
          3. Place the JAR in your `mods/` folder
          4. Launch Minecraft
          
          ### Requirements:
          - Minecraft 1.20.1
          - Forge 47.1.0+
          - Java 17+
          
          Co-authored-by: thurzinhos <joaquim.5922@aluno.pr.senac.br>
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/penguinlib-1.0.0.jar
        asset_name: penguinlib-${{ steps.get_version.outputs.VERSION }}-forge-1.20.1.jar
        asset_content_type: application/java-archive
